const sampleData = [
    {
        id: 1,
        logo: './logo/bitcoin-btc-logo.png',
        name: 'Bitcoin',
        symbol: 'BTC',
        price: 65000,
        change1h: 0.5,
        change24h: -1.2,
        change7d: 2.1,
        marketCap: '1.2T',
        volume24h: '35B',
        supply: '19M',
        maxSupply: '21M',
        chart: './chart/bitcoin-btc.png',
    },
    {
        id: 2,
        logo: './logo/ethereum-eth-logo.png',
        name: 'Ethereum',
        symbol: 'ETH',
        price: 3200,
        change1h: -0.3,
        change24h: 1.1,
        change7d: 3.5,
        marketCap: '400B',
        volume24h: '18B',
        supply: '120M',
        maxSupply: '∞',
        chart: './chart/ethereum-eth.png',
    },
    {
        id: 3,
        logo: './logo/tether-usdt-logo.png',
        name: 'Tether',
        symbol: 'USDT',
        price: 1.00,
        change1h: 0.0,
        change24h: 0.01,
        change7d: 0.02,
        marketCap: '90B',
        volume24h: '45B',
        supply: '90B',
        maxSupply: '∞',
        chart: './chart/tether-usdt.png',
    },
    {
        id: 4,
        logo: './logo/binance-coin-bnb-logo.png',
        name: 'Binance Coin',
        symbol: 'BNB',
        price: 550,
        change1h: 0.2,
        change24h: -0.5,
        change7d: 1.8,
        marketCap: '85B',
        volume24h: '1.2B',
        supply: '155M',
        maxSupply: '200M',
        chart: './chart/binance-coin-bnb.png',
    },
    {
        id: 5,
        logo: './logo/cardano-ada-logo.png',
        name: 'Cardano',
        symbol: 'ADA',
        price: 0.45,
        change1h: -0.3,
        change24h: 0.9,
        change7d: -2.3,
        marketCap: '16B',
        volume24h: '500M',
        supply: '35B',
        maxSupply: '45B',
        chart: './chart/cardano-ada.png',
    },
    {
        id: 6,
        logo: './logo/solana-sol-logo.png',
        name: 'Solana',
        symbol: 'SOL',
        price: 120.75,
        change1h: 1.2,
        change24h: 2.5,
        change7d: 5.8,
        marketCap: '50B',
        volume24h: '2.8B',
        supply: '415M',
        maxSupply: '∞',
        chart: './chart/solana-sol.png',
    }

];

export default sampleData;